### ISSUE TITLE
Tensorboard Box2d conflict

### ISSUE THREAD

**Issue by ghost** [martius-lab/laser-hockey-env#3]
Hi!
Did somebody manage to get tensorboard and box2d running under linux?
- If I am using python 3.6, I get 

> ModuleNotFoundError: No module named 'Box2D'

- `conda install -c kne pybox2d
`
get me all kinds of conflicts with torchvision-cpu, ... and wants to downgrade to python 2.7.
- building from the source described in https://github.com/jonasschneider/box2d-py/blob/master/INSTALL.md
still gets "ModuleNotFoundError: No module named 'Box2D'" despite of no compilation error.

- If I am using python 3.5, I get
`    serialized_pb=_b('\n(tensorboardX/proto/resource_handle.proto\x12\x0ctensorboardX\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
`
Downgrading protobuf 
` conda install -c anaconda protobuf=3.4.0` does not solve it.

**Comment by georgmartius** [comment]
Mh, looks messy. We are installing it though pip: pip install "gym[box2d]" 
use pip3 if you have both python 2 and 3 installed. 
The error message also points potentially to some problems in the load path.
